from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from typing import List, Optional
from pydantic import BaseModel, Field
import os

from .rag import get_answer_with_references

app = FastAPI(
    title="Knowledge Base Backend API",
    version="0.1.0",
    description="Backend APIs for file upload, Q&A, references, chart data, query history, and admin portal for a knowledge base using FastAPI.",
    openapi_tags=[
        {"name": "Files", "description": "Endpoints for file management and upload."},
        {"name": "Q&A", "description": "Endpoints for querying and getting answers with references."},
        {"name": "References", "description": "Reference retrieval endpoints."},
        {"name": "Charts", "description": "Endpoints for chart data."},
        {"name": "History", "description": "Endpoints for viewing query history."},
        {"name": "Admin", "description": "Admin portal endpoints."},
    ]
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QAQuery(BaseModel):
    """Question input for the /query endpoint."""
    question: str = Field(..., description="The user's natural language query.")

class QAResponse(BaseModel):
    """Standard response for Q&A endpoint."""
    answer: str = Field(..., description="The answer generated by the system.")
    references: List[str] = Field(default_factory=list, description="List of reference source links or IDs.")
    follow_up_questions: Optional[List[str]] = Field(default=None, description="Optional follow-up questions.")

class ReferenceList(BaseModel):
    """List of reference objects."""
    references: List[str] = Field(..., description="List of reference source links or IDs.")

class ChartParams(BaseModel):
    """Parameters for requesting chart data."""
    chart_type: str = Field(..., description="Type of chart requested, e.g. 'bar', 'pie', etc.")
    query: Optional[str] = Field(None, description="Supplementary natural language query for the chart.")

class ChartData(BaseModel):
    """Chart data for frontend visualization."""
    chart_type: str = Field(..., description="Type of chart.")
    labels: List[str] = Field(..., description="Axis/category labels.")
    values: List[float] = Field(..., description="Chart/series values.")

class QueryHistoryItem(BaseModel):
    question: str = Field(..., description="User's query")
    answer: str = Field(..., description="Answer provided")
    timestamp: str = Field(..., description="ISO 8601 timestamp of the query")

class HistoryList(BaseModel):
    history: List[QueryHistoryItem]

class AdminActionModel(BaseModel):
    """Model for admin actions."""
    action: str = Field(..., description="Admin action to perform")

@app.get("/", tags=["Health"])
def health_check():
    """Health check endpoint."""
    return {"message": "Healthy"}

# PUBLIC_INTERFACE
@app.post(
    "/upload",
    tags=["Files"],
    summary="Upload a file",
    response_description="Status of the upload"
)
async def upload_file(
    file: UploadFile = File(..., description="File to upload")
):
    """
    Upload a file (PDF, DOCX, TXT, etc.) for knowledge extraction and analysis.

    - **file**: The file being uploaded (various formats supported).
    - Returns: Status message and file metadata.
    """
    import datetime
    from . import utils
    from .models import metadata_from_upload

    # Save file
    saved_path = await utils.save_upload_file(file)
    # Get file size
    size = os.path.getsize(saved_path)
    # Build metadata
    metadata = metadata_from_upload(
        filename=file.filename,
        content_type=file.content_type,
        size=size,
        upload_time=datetime.datetime.utcnow(),
        path=saved_path
    )

    return {
        "status": "uploaded",
        "file": metadata.model_dump()
    }

# PUBLIC_INTERFACE
@app.post("/query", tags=["Q&A"], response_model=QAResponse, summary="Submit a query", response_description="QA answer and references")
async def submit_query(payload: QAQuery):
    """
    Submit a natural language query for Q&A against the knowledge base.

    - **question**: User's query.
    - Returns: Answer, references, and possible follow-up questions.
    """
    answer, references, follow_up = get_answer_with_references(payload.question)
    return QAResponse(
        answer=answer,
        references=references,
        follow_up_questions=follow_up
    )

# PUBLIC_INTERFACE
@app.get("/query", tags=["Q&A"], response_model=QAResponse, summary="Ask a query using a query parameter", response_description="QA answer and references")
async def get_query(question: str = None):
    """
    Retrieve an answer to a question using a query parameter (for testing/simple GET).

    - **question**: User's query string
    - Returns: Answer, references, and follow-up questions.
    """
    q = question if question is not None else ""
    answer, references, follow_up = get_answer_with_references(q)
    return QAResponse(
        answer=answer,
        references=references,
        follow_up_questions=follow_up
    )

# PUBLIC_INTERFACE
@app.get(
    "/references",
    tags=["References"],
    response_model=ReferenceList,
    summary="Get references",
    response_description="List of document sources used for answers"
)
async def get_references():
    """
    Retrieve list of reference files or sources available.

    Returns:
        ReferenceList: List of reference file names/links in the knowledge base.
    """
    # More realistic mock stub: could eventually fetch from state, DB, or file registry
    mock_references = [
        "Company_Policy_Handbook.pdf",
        "Employee_Guide_2023.docx",
        "Annual_Report_2022.pdf",
        "best-practices.txt",
        "finance-2021.xlsx"
    ]
    return ReferenceList(references=mock_references)

# PUBLIC_INTERFACE
@app.get(
    "/chart-data",
    tags=["Charts"],
    response_model=ChartData,
    summary="Get chart data",
    response_description="Chart data suitable for frontend visualizations"
)
async def get_chart_data(
    chart_type: str = Field(..., description="The kind of chart required (e.g., 'bar', 'line')."),
    query: Optional[str] = Field(None, description="Additional query for filtering/chart context.")
):
    """
    Retrieve chart data for the specified chart type and query.

    Parameters:
        chart_type (str): The chart type to generate ("bar", "line", etc.).
        query (Optional[str]): Chart context or filter.

    Returns:
        ChartData: Mock chart data for visualizations
    """
    if chart_type.lower() == "bar":
        return ChartData(
            chart_type="bar",
            labels=["HR", "Engineering", "Sales", "Support"],
            values=[18, 34, 21, 15]
        )
    elif chart_type.lower() == "line":
        return ChartData(
            chart_type="line",
            labels=["2020", "2021", "2022", "2023"],
            values=[1200, 1470, 1800, 2100]
        )
    elif chart_type.lower() == "pie":
        return ChartData(
            chart_type="pie",
            labels=["Completed", "In Progress", "Blocked"],
            values=[56, 34, 10]
        )
    else:
        # Default mock structure for unknown types
        return ChartData(
            chart_type=chart_type,
            labels=["A", "B", "C"],
            values=[10, 20, 15]
        )

# PUBLIC_INTERFACE
@app.get("/history", tags=["History"], response_model=HistoryList, summary="Get past queries", response_description="A list of previous queries and answers")
async def get_history():
    """
    Retrieve a history of previous queries and their answers.

    Returns a list of the user's past queries, answers, and timestamps.
    """
    # Stub response
    return HistoryList(history=[
        QueryHistoryItem(question="What is AI?", answer="AI stands for Artificial Intelligence.", timestamp="2024-06-25T10:30:14Z"),
        QueryHistoryItem(question="Show usage in 2023?", answer="Usage increased by 30%.", timestamp="2024-06-25T14:10:09Z")
    ])

# PUBLIC_INTERFACE
@app.get("/admin", tags=["Admin"], summary="View admin portal data", response_description="Admin portal data (stub)")
async def get_admin_portal():
    """
    Retrieve admin portal data (stub).

    Returns a placeholder for admin dashboard information, metrics, or logs.
    """
    return {"status": "Admin portal data (stub)"}

# PUBLIC_INTERFACE
@app.post("/admin", tags=["Admin"], summary="Perform admin action", response_description="Result of admin action (stub)")
async def perform_admin_action(action: AdminActionModel):
    """
    Perform an admin action, such as reprocessing or maintenance.

    - **action**: Action string specifying admin task.
    - Returns: Stub result for the action.
    """
    return {"result": f"Performed action: {action.action} (stub)"}
